Schema4.5
rdawg-pidinst/White-paper pull request #57
Opened 2024-10-03 15:16 UTC by tedhabermann

I checked the build from the last metadata.rst file and it looked fine. I thought one of the links might be bad, but I tested them all. I made a couple of other changes in this  branch, adding to the originals.

2024-10-03 15:42 UTC, tedhabermann commented
Looks like all checks have passed!

2024-10-30 18:10 UTC, RKrahl requested changes
Normally, it is best practice to clearly separate the roles: one proposes changes, another one reviews the proposal. But here, my review need to go deep into technical and formal details, including reStructuredText syntax errors. In this case, it is much easier to do the changes myself right away, rather than to explain them verbally.

Therefore, I submitted another PR #59 to amend your proposal. See that PR for a detailed list of changes. You may review the change in the rendered results by comparing [your version](https://rda-pidinst--57.org.readthedocs.build/en/57/datacite-cookbook/metadata.html) with the [updated version](https://rda-pidinst--59.org.readthedocs.build/en/59/datacite-cookbook/metadata.html). @tedhabermann, please let me know if you are happy with these changes.

2025-01-03 11:32 UTC, RKrahl commented
I now took your lack of feedback as silent consent and merged #59 into this branch.

2025-01-03 11:34 UTC, RKrahl approved these changes
With the amendments from #59 now ok.

2025-01-03 11:34 UTC, merged