Add a new subsection on dealing with unknown information
rdawg-pidinst/White-paper pull request #7
Opened 2021-02-09 12:45 UTC by RKrahl

As discussed in the last monthly meeting, I suggest to add a subsection that explains the use standard values for unknown information.

This PR depends on #4 because it modifies the section that has been moved in this other PR. It has been based on the `schema` branch to avoid a conflict. Nevertheless, the changes are independent of that PR. It may be rebased onto `develop` if desired.

Check the [result on RtD](https://rda-pidinst.readthedocs.io/en/unknown-values/white-paper/metadata-schema-recommendations.html#dealing-with-unknown-information).

2021-02-09 17:42 UTC, markusstocker commented on white-paper/metadata-schema-recommendations.rst
> +allow for soft-typing (e.g. *ownerName*), giving users the ability to
e.g., *ownerName* - add comma

2021-02-09 17:44 UTC, markusstocker commented on white-paper/metadata-schema-recommendations.rst
> +	   http://hdl.handle.net/21.T11998/0000-001A-3905-F displaying
The indentation here seems to be adding extra space in front of URLs - oddly enough only in front of URLs (as far as I can tell).

2021-02-09 17:52 UTC, markusstocker commented on white-paper/metadata-schema-recommendations.rst
> +In a similar way to common terminologies, persistent identifiers have
Minor, but I am not sure I agree that PIDs to something "in a similiar way to" terminologies. The identifier itself is similar in that it is a URI and terminologies use URIs to identify terms. But this is where the similarity ends, I am afraid. Yes, there is (usually) metadata associated to a PID but I don't think this is similar to the formal description of a term in your typical terminology. Not just do PID systems hardly agree on metadata syntax and semantics, they don't really encode any formal (i.e., machine readable) semantics in PID metadata as an (RDFS or OWL) terminology does. Anyhow, not a big deal.

2021-02-09 17:55 UTC, markusstocker commented on white-paper/metadata-schema-recommendations.rst
> +objects.  A related PID is the RRID, research resource identifier, which
Here it a bit unclear to what is RRID related. Perhaps: The research resource identifier (RRID) can be used to identify classes of instruments (models) and is thus related to PIDINST, which identifies instrument instances.

2021-02-09 17:58 UTC, markusstocker commented on white-paper/metadata-schema-recommendations.rst
> +not want to be named as the owner of the instrument taking the data.
"... instrument creating/generating the data", perhaps?

2021-02-09 17:59 UTC, markusstocker commented on white-paper/metadata-schema-recommendations.rst
> +give a reason, why it is missing.  PIDINST adopts for this purpose the
no comma before why

2021-02-09 18:00 UTC, markusstocker commented on white-paper/metadata-schema-recommendations.rst
> +give a reason, why it is missing.  PIDINST adopts for this purpose the
"For this purpose, PIDINST adopts the ..."

2021-02-09 18:02 UTC, markusstocker commented on white-paper/metadata-schema-recommendations.rst
> +.. _snip-schema-unknown-xml:
For some reason, this code block is now show in the "rich diff".

2021-02-09 18:04 UTC, markusstocker requested changes
I left some comments in the files using github.com - hope this is OK and you can find them.

2021-02-16 14:43 UTC, RKrahl commented on white-paper/metadata-schema-recommendations.rst
> +give a reason, why it is missing.  PIDINST adopts for this purpose the
Ok

2021-02-16 14:43 UTC, RKrahl commented on white-paper/metadata-schema-recommendations.rst
> +give a reason, why it is missing.  PIDINST adopts for this purpose the
Ok

2021-02-16 15:01 UTC, RKrahl commented on white-paper/metadata-schema-recommendations.rst
> +	   http://hdl.handle.net/21.T11998/0000-001A-3905-F displaying
Sorry, I can't recognize any extra space. If you look at [the result at rtd](https://rda-pidinst.readthedocs.io/en/unknown-values/white-paper/metadata-schema-recommendations.html#tab-schema-handle-record), the space in front of that URL is the same width as any other space between the words.

In any case, that change has not been introduced in this PR but rather in #2.

2021-02-16 15:02 UTC, RKrahl commented on white-paper/metadata-schema-recommendations.rst
> +.. _snip-schema-unknown-xml:
Not sure if I understand that comment.  Is anything wrong with that code block?

2021-02-16 15:09 UTC, RKrahl commented on white-paper/metadata-schema-recommendations.rst
> +allow for soft-typing (e.g. *ownerName*), giving users the ability to
This has not been changed in the PR. The text is the same as [in the default branch](https://rda-pidinst.readthedocs.io/en/latest/white-paper/metadata-schema.html#using-common-terminologies).  So your suggestion would constitute a new, independent change request.

2021-02-16 15:12 UTC, RKrahl commented on white-paper/metadata-schema-recommendations.rst
> +In a similar way to common terminologies, persistent identifiers have
This has not been changed in the PR. The text is the same as [in the default branch](https://rda-pidinst.readthedocs.io/en/latest/white-paper/metadata-schema.html#rrids).  So your suggestion would constitute a new, independent change request.

2021-02-16 15:12 UTC, RKrahl commented on white-paper/metadata-schema-recommendations.rst
> +objects.  A related PID is the RRID, research resource identifier, which
This has not been changed in the PR. The text is the same as [in the default branch](https://rda-pidinst.readthedocs.io/en/latest/white-paper/metadata-schema.html#rrids).  So your suggestion would constitute a new, independent change request.

2021-02-16 15:21 UTC, RKrahl commented on white-paper/metadata-schema-recommendations.rst
> +not want to be named as the owner of the instrument taking the data.
Not sure if I agree. Data is not something that is created or generated.  Data are in fact observations. I generally tend to use the formulation „the data has been collected using the instrument“, but in this particular phrase, I found „… might not want to be named as the owner of the instrument being used to collect the data“ somewhat clumsy, so I resorted to the more lightweight „… taking the data“.

2021-02-16 15:48 UTC, RKrahl commented
Many thanks @markusstocker for the comments.  I added a change following two of your suggestions.

Note that some of the comments are not related to this PR. I admit that this might be somewhat confusing, but this PR has been made on top of #4, otherwise it would have created a conflict with that other PR. That is why any change from #4 also appears to be a change from this PR as well. #4 in turn has moved a large fraction of the original text into a new section. So this text appears to have been added in #4, but in fact it has been left unchanged. Your comments 1, 3, and 4 relate to text portions that have not been changed in any of my PRs, see my reply above. It would make things easier if we keep the discussions about unrelated suggestions for changes separate.

I'm not able to follow your 2nd comment and I didn't quite understand your last one.

There is one suggestion concerning a formulation detail that may be debatable.

2021-02-26 11:08 UTC, louatbodc commented on white-paper/metadata-schema-recommendations.rst
> +In a similar way to common terminologies, persistent identifiers have
Although RRIDs are PIDs (handles), they are in fact being used in this case to classify the physical object as do vocabs (e.g. L22 and L05). It's used in the model identifier fields like controlled vocabs can be. Perhaps ' and accurately describe' should be removed because as you're right, there is a big difference between controlled vocabularies and PIDs. In my mind vocabs are used to define/enrich semantics while PIDs are used to timestamp/locate, not least differences in how they are registered etc. However, controlled vocabs (particularly in SKOS) should formally be associated to time field (created/modified) and as they are rendered as RDF web resources they can have resolvable URLs. Because of this it is completely feasible for a PID to be used in a similar way to a controlled vocab. In fact, some have thought you could use PIDs to identify versions of terms in controlled vocabulary collections. Though, personally I prefer to keep them separate.

I'm not sure I agree that PIDs couldn't encode any formal semantics. For example, SWE, SSN is based around building web semantics for unique IDs for sensors instances. There's nothing to stop these IDs being a PIDs. There's nothing to stop us encoding our metadata schema in RDF/Linked Data.

2021-02-26 11:11 UTC, louatbodc commented on white-paper/metadata-schema-recommendations.rst
> +give a reason, why it is missing.  PIDINST adopts for this purpose the
make it at least explicit

formally identify...

2021-02-26 11:12 UTC, louatbodc commented
Happy with section 'dealing with unknown information'. Will refer to main co-authors

2021-04-07 16:26 UTC, markusstocker commented on white-paper/metadata-schema-recommendations.rst
> +allow for soft-typing (e.g. *ownerName*), giving users the ability to
Moving to a separate PR

2021-04-07 16:29 UTC, markusstocker commented on white-paper/metadata-schema-recommendations.rst
> +	   http://hdl.handle.net/21.T11998/0000-001A-3905-F displaying
Seems to be an artefact on the visualization here on GitHub.

2021-04-07 16:31 UTC, markusstocker commented on white-paper/metadata-schema-recommendations.rst
> +In a similar way to common terminologies, persistent identifiers have
Since this was a mere comment, I am resolving it without further action.

2021-04-07 16:41 UTC, markusstocker commented on white-paper/metadata-schema-recommendations.rst
> +not want to be named as the owner of the instrument taking the data.
Interesting, somewhat, philosophical discussion. As I understand you, your point is that the data are out there to be "taken" never mind if anyone or anything does so, yes? Let's say, the property of temperature of ambient air exists in time and space, whether or not someone or something measures it. So, temperature is there to be taken. But is temperature the data or are the data the result of the process of measurement. I agree that temperature as a property of some physical entity exists but to me the resulting data aren't. In other words, isn't the property something else than the data resulting in measurement? From this point of view, the data don't exist and it is indeed the instrument that generates them. Consider this: If there are objective data out there to be taken, shouldn't different instruments taking the data then also take the same data (i.e., have the same values). Mostly it is so that different instruments return slightly different data (for the same thing measured). Doesn't this speak for a speratation of existing phenomenon and data about it, generated by the instrument in measurement? (Differences in the process of measurement explain why the resulting data can be different even though the same thing is measured?). Anyhow, just thinking outloud. Not suggesting we absolutely need to change this. Hence, in the interest of time I resolve this conversation.

2021-04-07 16:46 UTC, markusstocker commented on white-paper/metadata-schema-recommendations.rst
> +.. _snip-schema-unknown-xml:
I presume it is also an artefact of the rich diff on GitHub.

2021-04-07 16:52 UTC, markusstocker commented on white-paper/metadata-schema-recommendations.rst
> +give a reason, why it is missing.  PIDINST adopts for this purpose the
I guess @louatbodc proposed to change "make it at least explicit" to "formally identify", yes? To my understanding this is not about identifying information but to make it transparent that information has not been omitted inadvertetly. IMO "explicit" is fine.

2021-04-07 16:57 UTC, markusstocker commented on white-paper/metadata-schema-recommendations.rst
> +objects.  A related PID is the RRID, research resource identifier, which
Move to separate PR.

2021-04-07 16:58 UTC, markusstocker commented
I resolved some open issues in the review. As far as I can tell, one is left open. Perhaps @louatbodc you can take a look and make the call.

2021-04-15 11:09 UTC, louatbodc commented
@markusstocker Happy with the section. Please merge.

2021-04-16 07:53 UTC, merged